# Build the JAR file
FROM openjdk:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the target folder to the container
COPY target/bankapp-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application runs on
ENV PORT=10000
EXPOSE $PORT

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
